Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace rejestr_osob.Models
{
    public class Person
    {
        public int Id { get; set; }

        [Display(Name = "Imię")]
        public string firstName { get; set; }

        [Display(Name = "Nazwisko")]
        public string lastName { get; set; }

        [Display(Name = "Płeć")]
        public string gender { get; set; }

        [Display(Name = "Wiek")]
        public int age { get; set; }
    }
}

Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using rejestr_osob.Data;
using rejestr_osob.Models;

namespace rejestr_osob.Controllers
{
    public class PeopleController : Controller
    {
        private readonly PersonContext _context;

        public PeopleController(PersonContext context)
        {
            _context = context;
        }

        // GET: People
        public async Task<IActionResult> Index(string PersonGender = null)
        {
            ViewData["PersonGender"] = PersonGender;
            if(User.Identity.Name == "admin@admin.admin")
            {
                ViewData["isAdmin"] = true;
            }
            else
            {
                ViewData["isAdmin"] = false;
            }
            var persons = from p in _context.Person
                         select p;

            if (!String.IsNullOrEmpty(PersonGender) && PersonGender != "Wszyscy")
            {
                persons = persons.Where(s => s.gender.Contains(PersonGender));
            }

            return View(await persons.ToListAsync());
        }

        private object UserManager(ClaimsPrincipal user)
        {
            throw new NotImplementedException();
        }

        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,firstName,lastName,gender,age")] Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,firstName,lastName,gender,age")] Person person)
        {
            if (id != person.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Person.FindAsync(id);
            _context.Person.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(int id)
        {
            return _context.Person.Any(e => e.Id == id);
        }
    }
}

Views/People/Create.cshtml
@model rejestr_osob.Models.Person

@{
    ViewData["Title"] = "Dodaj";
}

<h1>Dodaj</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" data-val="true" data-val-required="To pole jest wymagane"/>
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" data-val="true" data-val-required="To pole jest wymagane"/>
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <select asp-for="gender" class="form-control">
                    <option value="Mężczyzna">Mężczyzna</option>
                    <option value="Kobieta">Kobieta</option>
                </select>
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="age" class="control-label"></label>
                <input asp-for="age" type="number" class="form-control" data-val="true" data-val-number="Wartość musi być liczbą" data-val-required="To pole jest wymagane" />
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót do listy</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/People/Delete.cshtml
@model rejestr_osob.Models.Person

@{
    ViewData["Title"] = "Usuń";
}

<h1>Usuń</h1>

<h3>Na pewno chcesz usunąć?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.age)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Zapisz" class="btn btn-danger" /> |
        <a asp-action="Index">Powrót do listy</a>
    </form>
</div>

Views/People/Details.cshtml
@model rejestr_osob.Models.Person

@{
    ViewData["Title"] = "Szczegóły";
}

<h1>Szczegóły</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.age)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a> |
    <a asp-action="Index">Powrót do listy</a>
</div>

Views/People/Edit.cshtml
@model rejestr_osob.Models.Person

@{
    ViewData["Title"] = "Edytuj";
}

<h1>Edytuj</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" data-val="true" data-val-required="To pole jest wymagane"/>
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" data-val="true" data-val-required="To pole jest wymagane"/>
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <select asp-for="gender" class="form-control">
                    <option value="Mężczyzna">Mężczyzna</option>
                    <option value="Kobieta">Kobieta</option>
                </select>
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="age" class="control-label"></label>
                <input asp-for="age" type="number" class="form-control" data-val="true" data-val-required="To pole jest wymagane"/>
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót do listy</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/People/Index.cshtml
@model IEnumerable<rejestr_osob.Models.Person>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Index";
}

<h1>Lista osób zaginionych</h1>

@if (SignInManager.IsSignedIn(User))
{
    <p>
        <a asp-action="Create" class="btn btn-primary">Dodaj</a>
    </p>
}

<form asp-controller="People" asp-action="Index" method="get">
    Filtruj wyniki wedłóg:
    <p>
        Płeć:
        <select name="PersonGender">
            @if ((string)ViewData["PersonGender"] == "Wszyscy")
            {
                <option value="Wszyscy" selected="selected">Wszyscy</option>
            }
            else
            {
                <option value="Wszyscy">Wszyscy</option>
            }
            @if ((string)ViewData["PersonGender"] == "Mężczyzna")
            {
                <option value="Mężczyzna" selected="selected">Mężczyzna</option>
            }
            else
            {
                <option value="Mężczyzna">Mężczyzna</option>
            }
            @if ((string)ViewData["PersonGender"] == "Kobieta")
            {
                <option value="Kobieta" selected="selected">Kobieta</option>
            }
            else
            {
                <option value="Kobieta">Kobieta</option>
            }
        </select>

        <input type="submit" value="Filtruj" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Imię
            </th>
            <th>
                Nazwisko
            </th>
            <th>
                Płeć
            </th>
            <th>
                Wiek
            </th>
            @if ((bool)ViewData["isAdmin"])
            {
                <th></th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.firstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.lastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.age)
                </td>
                @if ((bool)ViewData["isAdmin"])
                {
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edytuj</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Detale</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>